package com.wally.android.todo.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.wally.android.todo.entity.TodoTypeEntity;
import com.wally.android.todo.entity.UserInfoEntity;
import com.wally.android.todo.entity.TodoListEntity;

import com.wally.android.todo.dao.TodoTypeEntityDao;
import com.wally.android.todo.dao.UserInfoEntityDao;
import com.wally.android.todo.dao.TodoListEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig todoTypeEntityDaoConfig;
    private final DaoConfig userInfoEntityDaoConfig;
    private final DaoConfig todoListEntityDaoConfig;

    private final TodoTypeEntityDao todoTypeEntityDao;
    private final UserInfoEntityDao userInfoEntityDao;
    private final TodoListEntityDao todoListEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        todoTypeEntityDaoConfig = daoConfigMap.get(TodoTypeEntityDao.class).clone();
        todoTypeEntityDaoConfig.initIdentityScope(type);

        userInfoEntityDaoConfig = daoConfigMap.get(UserInfoEntityDao.class).clone();
        userInfoEntityDaoConfig.initIdentityScope(type);

        todoListEntityDaoConfig = daoConfigMap.get(TodoListEntityDao.class).clone();
        todoListEntityDaoConfig.initIdentityScope(type);

        todoTypeEntityDao = new TodoTypeEntityDao(todoTypeEntityDaoConfig, this);
        userInfoEntityDao = new UserInfoEntityDao(userInfoEntityDaoConfig, this);
        todoListEntityDao = new TodoListEntityDao(todoListEntityDaoConfig, this);

        registerDao(TodoTypeEntity.class, todoTypeEntityDao);
        registerDao(UserInfoEntity.class, userInfoEntityDao);
        registerDao(TodoListEntity.class, todoListEntityDao);
    }
    
    public void clear() {
        todoTypeEntityDaoConfig.clearIdentityScope();
        userInfoEntityDaoConfig.clearIdentityScope();
        todoListEntityDaoConfig.clearIdentityScope();
    }

    public TodoTypeEntityDao getTodoTypeEntityDao() {
        return todoTypeEntityDao;
    }

    public UserInfoEntityDao getUserInfoEntityDao() {
        return userInfoEntityDao;
    }

    public TodoListEntityDao getTodoListEntityDao() {
        return todoListEntityDao;
    }

}
